---
- name: Configure EC2 instance
  remote_user: ubuntu
  become: yes
  become_method: sudo
  hosts: all
  tasks:
    - name: Install Apache2
      apt:
        name: httpd
        state: present

    - name: Start Apache2
      service:
        name: httpd
        state: started
        enabled: yes
